// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF9_6yeri8Gs-V96lG5Qn5-7L5N6BowZE',
    appId: '1:923221179870:web:3a7b95af556422f414b14f',
    messagingSenderId: '923221179870',
    projectId: 'exohabit-76b1c',
    authDomain: 'exohabit-76b1c.firebaseapp.com',
    storageBucket: 'exohabit-76b1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu-Oq8e4W8LOBlD__4ylB1LKUJkr9Liv8',
    appId: '1:923221179870:android:7621ad9e0efe178914b14f',
    messagingSenderId: '923221179870',
    projectId: 'exohabit-76b1c',
    storageBucket: 'exohabit-76b1c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF9_6yeri8Gs-V96lG5Qn5-7L5N6BowZE',
    appId: '1:923221179870:web:10eeb5dcbe3cd3ff14b14f',
    messagingSenderId: '923221179870',
    projectId: 'exohabit-76b1c',
    authDomain: 'exohabit-76b1c.firebaseapp.com',
    storageBucket: 'exohabit-76b1c.firebasestorage.app',
  );
}
